### ISSUE TITLE
Test: Registration

### ISSUE THREAD

**Issue by piratefinn** [Pear-Trading/Foodloop-Mobile#2]
Check that during registration it is saving certain things locally

**Comment by piratefinn** [comment]
Registration seems to be running into a wall when HTTP POST'ing and not actually doing what it should on the server due to lack of response back.

**Comment by piratefinn** [comment]
With further investigation, it can do token registration from the app (though not phonegap serve, that seems to make the serve explode), but the submit to registration seems to send the username as undef, meaning it has no username to write to in the SQL Insert statement. A fix attempting to use the loaded in {{username}} in the placeholder as part of the data does not seem to send the username.

**Comment by piratefinn** [comment]
This has finally been resolved with changes to the javascript and server side code, at the same time also fixing an error where the server code used reserved keywords

**Comment by MichaelHallam** [comment]
You are doing a great job Finn.
Those of us who cant code can only marvel......
Michael
